dist: trusty
branches:
  only:
  - master
language: java
jdk: oraclejdk8
node_js:
  - "6"
script:
 - nvm install 6 
 - cd client && npm install && npm test && npm run build:prod
 - cd .. && ./mvnw test -B

