name: Build to Docker Hub

# Срабатывает при пуше в ветку master
on:
  push:
    branches: [master]

# Описание работы
jobs:
  build:
    # Используем последнюю версию Ubuntu
    runs-on: ubuntu-latest

    # Шаги выполнения задачи
    steps:
      # Клонируем репозиторий
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & publish the project
        run: |
          mvn clean package
          mvn compile jib:build -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} \
                                -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}
